---
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: containers/Dockerfile
    environment:
      - DB_HOST
      - DB_NAME
      - DB_PW
      - DB_USER
      - DB_PORT
      - DJANGO_SETTINGS_MODULE
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - media:/usr/src/app/media
      - .:/usr/src/app
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8000/status/?format=json"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
  db:
    image: bitnami/postgresql:12
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PW}
      - POSTGRES_USER=${DB_USER}
    expose:
      - 5432
    volumes:
      - db:/bitnami/postgresql

volumes:
  media:
  db:
