# Generated by Django 4.1.7 on 2023-03-25 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        help_text="Enter the position of the song in the playlist",
                        verbose_name="Position",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Element",
                "verbose_name_plural": "Elements",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the song",
                        max_length=100,
                        verbose_name="Song Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Song",
                "verbose_name_plural": "Songs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the playlist",
                        max_length=100,
                        verbose_name="Playlist Name",
                    ),
                ),
                (
                    "songs",
                    models.ManyToManyField(
                        help_text="Select the songs for the playlist",
                        related_name="playlist",
                        through="songs.Element",
                        to="songs.song",
                        verbose_name="Songs",
                    ),
                ),
            ],
            options={
                "verbose_name": "Playlist",
                "verbose_name_plural": "Playlists",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="element",
            name="playlist",
            field=models.ForeignKey(
                help_text="Select the playlist",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="element",
                to="songs.playlist",
                verbose_name="Playlist",
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="song",
            field=models.ForeignKey(
                help_text="Select the song",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="element",
                to="songs.song",
                verbose_name="Song",
            ),
        ),
    ]
